using Crestron.SimplSharp;                          				// For Basic SIMPL# Classes
using Crestron.SimplSharp.Net.Https;
using System;
using System.Linq;

namespace PhilipsHue
{
    /// <summary>
    /// Represents a Philips Hue light and provides methods and events for controlling and monitoring its state.
    /// </summary>
    /// <remarks>This class enables integration with Philips Hue lights, allowing for state changes and
    /// receiving updates about the light's status. It manages communication with the Philips Hue Bridge and exposes
    /// events for handling received light data. Thread safety is not guaranteed; callers should ensure appropriate
    /// synchronization if accessing instances from multiple threads.</remarks>
    public class PhilipsHueLight
    {
        /// <summary>
        /// Represents a method that handles detailed information about a light, including its name, type, state,
        /// brightness, color, and reachability.
        /// </summary>
        /// <param name="name">The name of the light.</param>
        /// <param name="type">The type of the light (for example, bulb, strip, etc.).</param>
        /// <param name="on">A string indicating whether the light is on. Expected values are "true" or "false".</param>
        /// <param name="bri">The brightness level of the light, typically in the range 0 to 254.</param>
        /// <param name="hue">The hue value of the light, typically in the range 0 to 65535.</param>
        /// <param name="sat">The saturation value of the light, typically in the range 0 to 254.</param>
        /// <param name="red">The red component of the light's color, as an integer value.</param>
        /// <param name="green">The green component of the light's color, as an integer value.</param>
        /// <param name="blue">The blue component of the light's color, as an integer value.</param>
        /// <param name="reachable">A string indicating whether the light is currently reachable. Expected values are "true" or "false".</param>
        public delegate void LightInfo(SimplSharpString name, SimplSharpString type, SimplSharpString on, ushort bri, ushort hue, ushort sat,
            ushort red, ushort green, ushort blue, SimplSharpString reachable);

        /// <summary>
        /// Represents the method that handles trace output events by receiving a trace message as a parameter.
        /// </summary>
        /// <param name="trace">The trace message to be handled. Cannot be null.</param>
        public delegate void OnTrace(SimplSharpString trace);

        /// <summary>
        /// Gets or sets the information for a new light to be added or configured.
        /// </summary>
        public LightInfo newLightInfo { get; set; }

        /// <summary>
        /// Gets or sets the delegate that is invoked when a trace event occurs.
        /// </summary>
        /// <remarks>Assign a method to this property to handle trace events generated by the system. The
        /// delegate receives information about the trace event, allowing custom logging or diagnostics.</remarks>
        public OnTrace newTrace { get; set; }

        private int ID;
        private string model;


        private event EventHandler<LightDataReceivedEventArgs> _OnLightDataReceived = delegate { };

        /// <summary>
        /// Occurs when new light data is received from the device.
        /// </summary>
        /// <remarks>Subscribe to this event to handle incoming light data as it becomes available. Event
        /// handlers receive a <see cref="LightDataReceivedEventArgs"/> instance containing the received data.</remarks>
        public event EventHandler<LightDataReceivedEventArgs> OnLightDataReceived
        {
            add
            {
                if (!_OnLightDataReceived.GetInvocationList().Contains(value))
                    _OnLightDataReceived += value;
            }
            remove
            {
                _OnLightDataReceived -= value;
            }
        }

        private string _address = "";

        /// <summary>
        /// Gets or sets the network address of the Philips Hue light client associated with this instance.
        /// </summary>
        /// <remarks>Changing the address will unregister the previous light client and register the new
        /// one. Event handlers for receiving light data are updated automatically when the address changes.</remarks>
        public string Address
        {
            get { return _address; }
            set
            {
                var address = _address;
                if (address != value)
                {
                    if (PhilipsHueBridge.TryGetLightClient(address, out var client))
                        client.OnLightDataReceived -= HandleReceiveData;

                    _address = value;

                    if (PhilipsHueBridge.RegisterLightClient(value))
                    {
                        PhilipsHueBridge.TryGetLightClient(value, out var newClient);
                        newClient.OnLightDataReceived += HandleReceiveData;
                    }
                }
            }
        }

        internal void HandleReceiveData(Object sender, LightDataReceivedEventArgs Data)
        {
            ushort red = 0;
            ushort green = 0;
            ushort blue = 0;

            if (Data.XY != null)
            {
                if (float.Parse(Data.XY[0]) > 0)
                {
                    ColourConverter.Point point = new ColourConverter.Point(double.Parse(Data.XY[0]), double.Parse(Data.XY[1]));
                    ColourConverter.RGBColour RGB = ColourConverter.XYtoRGB(point, Data.Model);
                    red = Convert.ToUInt16(RGB.red * 255);
                    green = Convert.ToUInt16(RGB.green * 255);
                    blue = Convert.ToUInt16(RGB.blue * 255);

                }
            }

            newLightInfo(Data.Name, Data.Type, Data.On.ToString(), Data.Bri, Data.Hue, Data.Sat, red, green,
                blue, Data.Reachable.ToString());
            ID = Data.ID;
            model = Data.Model;
        }

        /// <summary>
        /// Sends a command to update the state of a Philips Hue light based on the specified type and state values.
        /// </summary>
        /// <remarks>If the type is "xy", all three state parameters are used to define the RGB color,
        /// which is converted to XY color space before sending to the light. For other types, only state1 is used. The
        /// method sends the command to the Philips Hue Bridge and logs the request body for tracing.</remarks>
        /// <param name="type">The type of state to set for the light. Supported values include "on", "bri", "hue", "sat", and "xy".</param>
        /// <param name="state1">The primary state value to apply. For "on", use 0 for off and 1 for on. For "bri", "hue", and "sat",
        /// specifies the corresponding value. For "xy", represents the red color component (0–255).</param>
        /// <param name="state2">For the "xy" type, specifies the green color component (0–255). Ignored for other types.</param>
        /// <param name="state3">For the "xy" type, specifies the blue color component (0–255). Ignored for other types.</param>
        public void LightState(string type, ushort state1, ushort state2, ushort state3)
        {         
            try
            {
                string body = "";

                if (type == "on")
                {
                    if (state1 == 0) body = "{\"on\":false}";
                    else if (state1 == 1) body = "{\"on\":true}";
                }
                else if (type == "bri") body = String.Format("{{\"bri\":{0}}}", state1);
                else if (type == "hue") body = String.Format("{{\"hue\":{0}}}", state1);
                else if (type == "sat") body = String.Format("{{\"sat\":{0}}}", state1);
                else if (type == "xy")
                {
                    double red = state1 / 255.0;
                    double green = state2 / 255.0;
                    double blue = state3 / 255.0;

                    ColourConverter.RGBColour RGB = new ColourConverter.RGBColour(red, green, blue);
                    ColourConverter.Point point = ColourConverter.RgbToXY(RGB, model); 

                    body = String.Format("{{\"xy\":[{0}, {1}]}}", point.x, point.y);
                }

                newTrace(body);

                PhilipsHueBridge.SendCommand(String.Format("{0}api/{1}/lights/{2}/state", PhilipsHueBridge.BaseUrl, PhilipsHueBridge.Username, ID),
                    body, RequestType.Put, 2, 0);
            }

            catch (Exception e)
            {
                CrestronConsole.PrintLine(e.Message + "\n" + e.StackTrace);
            }
        }

        /// <summary>
        /// Sends a request to retrieve the current state and attributes of the specified Philips Hue light from the
        /// bridge.
        /// </summary>
        /// <remarks>This method communicates with the Philips Hue Bridge using the configured base URL
        /// and user credentials. The light is identified by its unique ID. Ensure that the bridge connection and
        /// credentials are properly configured before calling this method.</remarks>
        public void GetLight()
        {
            PhilipsHueBridge.SendCommand(String.Format("{0}api/{1}/lights/{2}", PhilipsHueBridge.BaseUrl, PhilipsHueBridge.Username, ID), "",
                RequestType.Get, 3, ID);
        }
    }
}